# -*- coding: utf-8 -*-
"""Tiket_Kereta

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l2wIrRJmjfFGJ12Ya7ausZGnlxHb9q8H
"""

def menu():
    print("="*45)
    print("|  SELAMAT DATANG DI AGEN TIKET KERETA API  |")
    print("|___________________________________________|")
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("|___________________________________________|")
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("|___________________________________________|")
    print("|          JURUSAN JAKARTA - MALANG         |")
    print("="*45)

    print("="*45)
    print("|                 MENU UTAMA                |")
    print("="*45)
    print("|  1. RUTE KERETA API                       |")
    print("|  2. PEMESANAN TIKET KERETA API            |")
    print("|  3. KELUAR PROGRAM                        |")
    print("="*45)
    pilihan1 = input("Masukkan pilihan [1-3]: ")
    if pilihan1 == "1":
        rute()
    elif pilihan1 == "2":
        pesan()
    elif pilihan1 == "3":
        exit()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def rute():
    print("="*45)
    print("|              RUTE KERETA API              |")
    print("="*45)
    print("|  1. JURUSAN JAKARTA - SURABAYA            |")
    print("|  2. JURUSAN SURABAYA - JAKARTA            |")
    print("|  3. JURUSAN JAKARTA - MALANG              |")
    print("="*45)
    pilihan2 = input('Apakah Anda ingin melakukan pemesanan tiket? [ya/tidak]: ')
    if pilihan2.upper() == "YA":
        pesan()
    elif pilihan2.upper() == "TIDAK":
        pilihan3 = input("Kembali ke menu utama[1] atau keluar program[2]? ")
        if pilihan3 == "1":
            menu()
        elif pilihan3 == "2":
            exit()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def pesan():
    print("="*45)
    print("|        PEMESANAN TIKET KERETA API         |")
    print("="*45)
    print("|  1. JURUSAN JAKARTA - SURABAYA            |")
    print("|  2. JURUSAN SURABAYA - JAKARTA            |")
    print("|  3. JURUSAN JAKARTA - MALANG              |")
    print("="*45)
    pilihan4 = input("Silahkan pilih jurusan kereta api: ")
    if pilihan4 == "1":
        keberangkatan.berangkat1()
    elif pilihan4 == "2":
        keberangkatan.berangkat2()
    elif pilihan4 == "3":
        keberangkatan.malang()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def exit():
    print("="*45)
    print("|              KELUAR PROGRAM               |")
    print("="*45)
    print("|      ANDA TELAH KELUAR DARI PROGRAM       |")
    print("|    TERIMA KASIH SUDAH MENGUNJUNGI KAMI    |")
    print("="*45)
    
class keberangkatan():
    def malang():
        print("="*45)
        print("|           STASIUN KEBERANGKATAN           |")
        print("="*45)
        print("|          JURUSAN JAKARTA - MALANG         |")
        print("|___________________________________________|")
        print("|  1. STASIUN GAMBIR                        |")
        print("|  2. STASIUN PASAR SENEN                   |")
        print("="*45)
        pilmal = input("Silahkan pilih stasiun keberangkatan [1-2]: ")
        if pilmal == "1":
            kedatangan.datmal1()
        elif pilmal == "2":
            kedatangan.datmal2()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
    def berangkat1():
        print("="*45)
        print("|           STASIUN KEBERANGKATAN           |")
        print("="*45)
        print("|         JURUSAN JAKARTA - SURABAYA        |")
        print("|___________________________________________|")
        print("|  1. STASIUN GAMBIR                        |")
        print("|  2. STASIUN PASAR SENEN                   |")
        print("="*45)
        pilihan5 = input("Silahkan pilih stasiun keberangkatan [1-2]: ")
        if pilihan5 == "1":
            kedatangan.kedatangan1()
        elif pilihan5 == "2":
            kedatangan.kedatangan2()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
    def berangkat2():
        print("="*45)
        print("|           STASIUN KEBERANGKATAN           |")
        print("="*45)
        print("|         JURUSAN SURABAYA - JAKARTA        |")
        print("|___________________________________________|")
        print("|  1. STASIUN GUBENG                        |")
        print("|  2. STASIUN PASAR TURI                    |")
        print("="*45)
        pilihan6 = input("Silahkan pilih stasiun keberangkatan [1-2]: ")
        if pilihan6 == "1":
            kedatangan.kedatangan3()
        elif pilihan6 == "2":
            kedatangan.kedatangan4()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
            
class kedatangan(keberangkatan):  
    def datmal1():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|          JURUSAN JAKARTA - MALANG         |")
        print("|___________________________________________|")
        print("|  1. STASIUN MALANG                        |")
        print("|  2. STASIUN LAINNYA                       |")
        print("="*45)
        jmg = input("Silahkan pilih stasiun kedatangan [1-3]: ")
        if jmg == "1":
            JMG()
        elif jmg == "2":
            print("Perjalanan Kereta Jakarta - Malang menggunakan")
            print("jalur yang sama dengan Jakarta - Surabaya")
            kedatangan.kedatangan5()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
            
    def datmal2():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|          JURUSAN JAKARTA - MALANG         |")
        print("|___________________________________________|")
        print("|  1. STASIUN MALANG                        |")
        print("|  2. STASIUN LAINNYA                       |")
        print("="*45)
        jmp = input("Silahkan pilih stasiun kedatangan [1-3]: ")
        if jmp == "1":
            JMP()
        elif jmp == "2":
            print("Perjalanan Kereta Jakarta - Malang menggunakan")
            print("jalur yang sama dengan Jakarta - Surabaya")
            kedatangan.kedatangan5()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
    def kedatangan1():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|         JURUSAN JAKARTA - SURABAYA        |")
        print("|___________________________________________|")
        print("|  1. STASIUN GUBENG                        |")
        print("|  2. STASIUN PASAR TURI                    |")
        print("|  3. STASIUN LAINNYA                       |")
        print("="*45)
        pilihan71 = input("Silahkan pilih stasiun kedatangan [1-3]: ")
        if pilihan71 == "1":
            JSGG()
        elif pilihan71 == "2":
            JSGP()
        elif pilihan71 == "3":
            kedatangan.kedatangan5()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
            
    def kedatangan2():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|         JURUSAN JAKARTA - SURABAYA        |")
        print("|___________________________________________|")
        print("|  1. STASIUN GUBENG                        |")
        print("|  2. STASIUN PASAR TURI                    |")
        print("|  3. STASIUN LAINNYA                       |")
        print("="*45)
        pilihan72 = input("Silahkan pilih stasiun kedatangan [1-3]: ")
        if pilihan72 == "1":
            JSPG()
        elif pilihan72 == "2":
            JSPP()
        elif pilihan72 == "3":
            kedatangan.kedatangan6()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
    def kedatangan3():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|         JURUSAN SURABAYA - JAKARTA        |")
        print("|___________________________________________|")
        print("|  1. STASIUN GAMBIR                        |")
        print("|  2. STASIUN PASAR SENEN                   |")
        print("|  3. STASIUN LAINNYA                       |")
        print("="*45)
        pilihan81 = input("Silahkan pilih stasiun kedatangan [1-3]: ")
        if pilihan81 == "1":
            SJGG()
        elif pilihan81 == "2":
            SJPG()
        elif pilihan81 == "3":
            kedatangan.kedatangan7()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
            
    def kedatangan4():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|         JURUSAN SURABAYA - JAKARTA        |")
        print("|___________________________________________|")
        print("|  1. STASIUN GAMBIR                        |")
        print("|  2. STASIUN PASAR SENEN                   |")
        print("|  3. STASIUN LAINNYA                       |")
        print("="*45)
        pilihan82 = input("Silahkan pilih stasiun kedatangan [1-3]: ")
        if pilihan82 == "1":
            SJGP()
        elif pilihan82 == "2":
            SJPP()
        elif pilihan82 == "3":
            kedatangan.kedatangan8()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
    def kedatangan5():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|          PILIHAN PROVINSI STASIUN         |")
        print("|___________________________________________|")
        print("|  1. JAWA BARAT                            |")
        print("|  2. JAWA TENGAH                           |")
        print("|  3. JAWA TIMUR                            |")
        print("="*45)
        pilihan91 = input("Silahkan pilih provinsi stasiun kedatangan [1-3]: ")
        if pilihan91 == "1":
            JSGB()
        elif pilihan91 == "2":
            JSGE()
        elif pilihan91 == "3":
            JSGI()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
            
    def kedatangan6():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|          PILIHAN PROVINSI STASIUN         |")
        print("|___________________________________________|")
        print("|  1. JAWA BARAT                            |")
        print("|  2. JAWA TENGAH                           |")
        print("|  3. JAWA TIMUR                            |")
        print("="*45)
        pilihan92 = input("Silahkan pilih provinsi stasiun kedatangan [1-3]: ")
        if pilihan92 == "1":
            JSPB()
        elif pilihan92 == "2":
            JSPE()
        elif pilihan92 == "3":
            JSPI()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
            
    def kedatangan7():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|          PILIHAN PROVINSI STASIUN         |")
        print("|___________________________________________|")
        print("|  1. JAWA BARAT                            |")
        print("|  2. JAWA TENGAH                           |")
        print("|  3. JAWA TIMUR                            |")
        print("="*45)
        pilihan93 = input("Silahkan pilih provinsi stasiun kedatangan [1-3]: ")
        if pilihan93 == "1":
            SJGB()
        elif pilihan93 == "2":
            SJGE()
        elif pilihan93 == "3":
            SJGI()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
            
    def kedatangan8():
        print("="*45)
        print("|             STASIUN KEDATANGAN            |")
        print("="*45)
        print("|          PILIHAN PROVINSI STASIUN         |")
        print("|___________________________________________|")
        print("|  1. JAWA BARAT                            |")
        print("|  2. JAWA TENGAH                           |")
        print("|  3. JAWA TIMUR                            |")
        print("="*45)
        pilihan94 = input("Silahkan pilih provinsi stasiun kedatangan [1-3]: ")
        if pilihan94 == "1":
            SJPB()
        elif pilihan94 == "2":
            SJPE()
        elif pilihan94 == "3":
            SJPI()
        else:
            print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def JMG():
    "Jurusan Jakarta Malang dengan Stasiun Keberangkatan Gambir dan Stasiun Kedatangan Malang"
    print("="*45)
    print("|          JURUSAN JAKARTA - MALANG         |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GAMBIR                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                  MALANG                   |")
    print("|___________________________________________|")
    print("| No | Nama Kereta Api | Kelas     | Harga  |")
    print("|  1 | Gajayana        | Eksekutif | 650.000|")
    print("|  2 | Brawijaya       | Eksekutif | 800.000|")
    print("="*45)
    JMG = input("Silahkan pilih kereta api yang diinginkan [1-2]: ")
    if JMG == "1":
        bayar332()
    elif JMG == "2":
        bayar341()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def JMP():
    "Jurusan Jakarta Malang dengan Stasiun Keberangkatan Pasar Sene dan Stasiun Kedatangan Malang"
    print("="*45)
    print("|          JURUSAN JAKARTA - MALANG         |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|               PASAR SENEN                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                  MALANG                   |")
    print("|___________________________________________|")
    print("| No | Nama Kereta Api | Kelas     | Harga  |")
    print("|  1 | Jayabaya        | Eksekutif | 520.000|")
    print("|  2 | Majapahit       | Ekonomi   | 450.000|")
    print("|  3 | Majapahit       | Eksekutif | 650.000|")
    print("="*45)
    JMP = input("Silahkan pilih kereta api yang diinginkan [1-2]: ")
    if JMP == "1":
        bayar231()
    elif JMP == "2":
        bayar131()
    elif JMP == "3":
        bayar332()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
def JSGG():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Gambir dan Stasiun Kedatangan Gubeng"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GAMBIR                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                  GUBENG                   |")
    print("|___________________________________________|")
    print("|               PILIHAN KELAS               |")
    print("|___________________________________________|")
    print("|  1. EKONOMI                               |")
    print("|  2. BISNIS                                |")
    print("|  3. EKSEKUTIF                             |")
    print("|  4. LUXURY                                |")
    print("="*45)
    pilkel1 = input("Silahkan pilih kelas yang diinginkan [1-4]: ")
    if pilkel1 == "1":
        kel11()
    elif pilkel1 == "2":
        kel11()
    elif pilkel1 == "3":
        kel13()
    elif pilkel1 == "4":
        kel11()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def JSPG():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Pasar Senen dan Stasiun Kedatangan Gubeng"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|               PASAR SENEN                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                  GUBENG                   |")
    print("|___________________________________________|")
    print("|               PILIHAN KELAS               |")
    print("|___________________________________________|")
    print("|  1. EKONOMI                               |")
    print("|  2. BISNIS                                |")
    print("|  3. EKSEKUTIF                             |")
    print("|  4. LUXURY                                |")
    print("="*45)
    pilkel2 = input("Silahkan pilih kelas yang diinginkan [1-4]: ")
    if pilkel2 == "1":
        kel21()
    elif pilkel2 == "2":
        kel11()
    elif pilkel2 == "3":
        kel23()
    elif pilkel2 == "4":
        kel11()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
def JSGP():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Gambir dan Stasiun Kedatangan Pasar Turi"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GAMBIR                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                PASAR TURI                 |")
    print("|___________________________________________|")
    print("|               PILIHAN KELAS               |")
    print("|___________________________________________|")
    print("|  1. EKONOMI                               |")
    print("|  2. BISNIS                                |")
    print("|  3. EKSEKUTIF                             |")
    print("|  4. LUXURY                                |")
    print("="*45)
    pilkel3 = input("Silahkan pilih kelas yang diinginkan [1-4]: ")
    if pilkel3 == "1":
        kel11()
    elif pilkel3 == "2":
        kel11()
    elif pilkel3 == "3":
        kel33()
    elif pilkel3 == "4":
        kel34()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
              
def JSPP():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Pasar Senen dan Stasiun Kedatangan Pasar Turi"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|               PASAR SENEN                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                PASAR TURI                 |")
    print("|___________________________________________|")
    print("|               PILIHAN KELAS               |")
    print("|___________________________________________|")
    print("|  1. EKONOMI                               |")
    print("|  2. BISNIS                                |")
    print("|  3. EKSEKUTIF                             |")
    print("|  4. LUXURY                                |")
    print("="*45)
    pilkel4 = input("Silahkan pilih kelas yang diinginkan [1-4]: ")
    if pilkel4 == "1":
        kel41()
    elif pilkel4 == "2":
        kel42()
    elif pilkel4 == "3":
        kel43()
    elif pilkel4 == "4":
        kel11()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
def SJGG():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Gubeng dan Stasiun Kedatangan Gambir"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GUBENG                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                  GAMBIR                   |")
    print("|___________________________________________|")
    print("|               PILIHAN KELAS               |")
    print("|___________________________________________|")
    print("|  1. EKONOMI                               |")
    print("|  2. BISNIS                                |")
    print("|  3. EKSEKUTIF                             |")
    print("|  4. LUXURY                                |")
    print("="*45)
    pilkel5 = input("Silahkan pilih kelas yang diinginkan [1-4]: ")
    if pilkel5 == "1":
        kel51()
    elif pilkel5 == "2":
        kel51()
    elif pilkel5 == "3":
        kel53()
    elif pilkel5 == "4":
        kel51()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
def SJGP():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Gubeng dan Stasiun Kedatangan Pasar Senen"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GUBENG                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|               PASAR SENEN                 |")
    print("|___________________________________________|")
    print("|               PILIHAN KELAS               |")
    print("|___________________________________________|")
    print("|  1. EKONOMI                               |")
    print("|  2. BISNIS                                |")
    print("|  3. EKSEKUTIF                             |")
    print("|  4. LUXURY                                |")
    print("="*45)
    pilkel6 = input("Silahkan pilih kelas yang diinginkan [1-4]: ")
    if pilkel6 == "1":
        kel61()
    elif pilkel6 == "2":
        kel51()
    elif pilkel6 == "3":
        kel63()
    elif pilkel6 == "4":
        kel51()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
def SJPG():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Pasar Turi dan Stasiun Kedatangan Gambir"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                PASAR TURI                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                  GAMBIR                   |")
    print("|___________________________________________|")
    print("|               PILIHAN KELAS               |")
    print("|___________________________________________|")
    print("|  1. EKONOMI                               |")
    print("|  2. BISNIS                                |")
    print("|  3. EKSEKUTIF                             |")
    print("|  4. LUXURY                                |")
    print("="*45)
    pilkel7 = input("Silahkan pilih kelas yang diinginkan [1-4]: ")
    if pilkel7 == "1":
        kel51()
    elif pilkel7 == "2":
        kel51()
    elif pilkel7 == "3":
        kel73()
    elif pilkel7 == "4":
        kel74()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
def SJPP():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Pasar Turi dan Stasiun Kedatangan Pasar Senen"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                PASAR TURI                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|               PASAR SENEN                 |")
    print("|___________________________________________|")
    print("|               PILIHAN KELAS               |")
    print("|___________________________________________|")
    print("|  1. EKONOMI                               |")
    print("|  2. BISNIS                                |")
    print("|  3. EKSEKUTIF                             |")
    print("|  4. LUXURY                                |")
    print("="*45)
    pilkel8 = input("Silahkan pilih kelas yang diinginkan [1-4]: ")
    if pilkel8 == "1":
        kel81()
    elif pilkel8 == "2":
        kel82()
    elif pilkel8 == "3":
        kel83()
    elif pilkel8 == "4":
        kel51()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
def JSGB():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Gambir dan Stasiun Kedatangan di Jawa Barat"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GAMBIR                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                JAWA BARAT                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Cirebon         | Eksekutif | 650.000|")
    print("|  2 | Cirebon         | Luxury    | 800.000|")
    print("|  3 | Jatibarang      | Eksekutif | 650.000|")
    print("="*45)
    JSGB = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-3]: ")
    if JSGB == "1":
        bayar332()
    elif JSGB == "2":
        bayar341()
    elif JSGB == "3":
        bayar332()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def JSPB():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Pasar Senen dan Stasiun Kedatangan di Jawa Barat"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|               PASAR SENEN                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                JAWA BARAT                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Bekasi          | Ekonomi   | 450.000|")
    print("|  2 | Bekasi          | Eksekutif | 650.000|")
    print("|  3 | Karawang        | Ekonomi   | 450.000|")
    print("|  4 | Karawang        | Eksekutif | 650.000|")
    print("|  5 | Cikampek        | Ekonomi   | 450.000|")
    print("|  6 | Cikampek        | Eksekutif | 650.000|")
    print("|  7 | Pegaden Baru    | Ekonomi   | 450.000|")
    print("|  8 | Pegaden Baru    | Eksekutif | 650.000|")
    print("|  9 | Haurgeulis      | Ekonomi   | 450.000|")
    print("| 10 | Haurgeulis      | Eksekutif | 650.000|")
    print("| 11 | Jatibarang      | Ekonomi   | 450.000|")
    print("| 12 | Jatibarang      | Bisnis    | 520.000|")
    print("| 13 | Jatibarang      | Eksekutif | 650.000|")
    print("| 14 | Cirebon         | Ekonomi   | 450.000|")
    print("| 15 | Cirebon         | Bisnis    | 520.000|")
    print("| 16 | Cirebon         | Eksekutif | 650.000|")
    print("| 17 |Cirebon Prujakan | Ekonomi   | 450.000|")
    print("| 18 |Cirebon Prujakan | Eksekutif | 650.000|")
    print("| 19 | Prujakan        | Ekonomi   | 450.000|")
    print("| 20 | Prujakan        | Eksekutif | 650.000|")
    print("| 21 | Babakan         | Ekonomi   | 450.000|")
    print("| 22 | Babakan         | Eksekutif | 650.000|")
    print("| 23 | Ciledug         | Ekonomi   | 450.000|")
    print("| 24 | Ciledug         | Eksekutif | 650.000|")
    print("="*45)
    JSPB = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-24]: ")
    neko = ["1","3","5","7","9","11","14","17","19","21","23"]
    nebis = ["12","15"]
    netif = ["2","4","6","8","10","13","16","18","20","22","24"]
    if JSPB in neko:
        bayar131()
    elif JSPB in nebis:
        bayar231()
    elif JSPB in netif:
        bayar332()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
              
def SJGB():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Gubeng dan Stasiun Kedatangan di Jawa Barat"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GUBENG                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                JAWA BARAT                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Karawang        | Ekonomi   | 450.000|")
    print("|  2 | Karawang        | Eksekutif | 650.000|")
    print("|  3 | Cikampek        | Ekonomi   | 450.000|")
    print("|  4 | Cikampek        | Eksekutif | 650.000|")
    print("|  5 | Pegaden Baru    | Ekonomi   | 450.000|")
    print("|  6 | Pegaden Baru    | Eksekutif | 650.000|")
    print("|  7 | Haurgeulis      | Ekonomi   | 450.000|")
    print("|  8 | Haurgeulis      | Eksekutif | 650.000|")
    print("|  9 | Jatibarang      | Ekonomi   | 450.000|")
    print("| 10 | Jatibarang      | Eksekutif | 650.000|")
    print("| 11 | Cirebon         | Ekonomi   | 450.000|")
    print("| 12 | Cirebon         | Eksekutif | 650.000|")
    print("| 13 | Prujakan        | Ekonomi   | 450.000|")
    print("| 14 | Prujakan        | Eksekutif | 650.000|")
    print("| 15 | Ciledug         | Ekonomi   | 450.000|")
    print("| 16 | Ciledug         | Eksekutif | 650.000|")
    print("="*45)
    SJGB = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-16]: ")
    guko = ["1","3","5","7","9","11","13","15"]
    gutif = ["2","4","6","8","10","12","14","16"]
    if SJGB in guko:
        bayar131()
    elif SJGB in gutif:
        bayar332()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
              
def SJPB():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Pasar Turi dan Stasiun Kedatangan di Jawa Barat"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                PASAR TURI                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                JAWA BARAT                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Bekasi          | Ekonomi   | 450.000|")
    print("|  2 | Bekasi          | Eksekutif | 650.000|")
    print("|  3 | Karawang        | Ekonomi   | 450.000|")
    print("|  4 | Karawang        | Eksekutif | 650.000|")
    print("|  5 | Cikampek        | Ekonomi   | 450.000|")
    print("|  6 | Cikampek        | Eksekutif | 650.000|")
    print("|  7 | Pegaden Baru    | Ekonomi   | 450.000|")
    print("|  8 | Pegaden Baru    | Eksekutif | 650.000|")
    print("|  9 | Haurgeulis      | Ekonomi   | 450.000|")
    print("| 10 | Haurgeulis      | Eksekutif | 650.000|")
    print("| 11 | Jatibarang      | Ekonomi   | 450.000|")
    print("| 12 | Jatibarang      | Bisnis    | 520.000|")
    print("| 13 | Jatibarang      | Eksekutif | 650.000|")
    print("| 14 | Cirebon         | Ekonomi   | 450.000|")
    print("| 15 | Cirebon         | Bisnis    | 520.000|")
    print("| 16 | Cirebon         | Eksekutif | 650.000|")
    print("| 17 |Cirebon Prujakan | Ekonomi   | 450.000|")
    print("| 18 |Cirebon Prujakan | Eksekutif | 650.000|")
    print("| 19 | Prujakan        | Ekonomi   | 450.000|")
    print("| 20 | Prujakan        | Eksekutif | 650.000|")
    print("| 21 | Babakan         | Ekonomi   | 450.000|")
    print("| 22 | Babakan         | Eksekutif | 650.000|")
    print("="*45)
    SJPB = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-22]: ")
    teko = ["1","3","5","7","9","11","14","17","19","21"]
    tekbis = ["12","15"]
    tektif = ["2","4","6","8","10","13","16","18","20","22"]
    if SJPB in teko:
        bayar131()
    elif SJPB in tekbis:
        bayar231()
    elif SJPB in tektif:
        bayar332()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
              
def JSGE():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Gambir dan Stasiun Kedatangan di Jawa Tengah"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GAMBIR                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|               JAWA TENGAH                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Tegal           | Eksekutif | 650.000|")
    print("|  2 | Tegal           | Luxury    | 800.000|")
    print("|  3 | Pekalongan      | Eksekutif | 650.000|")
    print("|  4 | Pekalongan      | Luxury    | 800.000|")
    print("|  5 | Semarang Tawang | Eksekutif | 650.000|")
    print("|  6 | Semarang Tawang | Luxury    | 800.000|")
    print("|  7 | Ngrombo         | Eksekutif | 650.000|")
    print("|  8 | Ngrombo         | Luxury    | 800.000|")
    print("|  9 | Cepu            | Eksekutif | 650.000|")
    print("| 10 | Cepu            | Luxury    | 800.000|")
    print("| 11 | Purwokerto      | Eksekutif | 650.000|")
    print("| 12 | Purwokerto      | Luxury    | 800.000|")
    print("| 13 | Kroya           | Eksekutif | 650.000|")
    print("| 14 | Kroya           | Luxury    | 800.000|")
    print("| 15 | Kebumen         | Eksekutif | 650.000|")
    print("| 16 | Kebumen         | Luxury    | 800.000|")
    print("| 17 | Kutoarjo        | Eksekutif | 650.000|")
    print("| 18 | Kutoarjo        | Luxury    | 800.000|")
    print("| 19 | Yogyakarta      | Eksekutif | 650.000|")
    print("| 20 | Yogyakarta      | Luxury    | 800.000|")
    print("| 21 | Solo Balapan    | Eksekutif | 650.000|")
    print("| 22 | Solo Balapan    | Luxury    | 800.000|")
    print("="*45)
    JSGE = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-22]: ")
    eks = ["1","3","5","7","9","11","13","15","17","19","21"]
    lux = ["2","4","6","8","10","12","14","16","18","20","22"]
    if JSGE in eks:
        bayar332()
    elif JSGE in lux:
        bayar341()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
              
def JSPE():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Pasar Senen dan Stasiun Kedatangan di Jawa Tengah"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|               PASAR SENEN                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|               JAWA TENGAH                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Tanjung         | Ekonomi   | 450.000|")
    print("|  2 | Tanjung         | Eksekutif | 650.000|")
    print("|  3 | Brebes          | Ekonomi   | 450.000|")
    print("|  4 | Brebes          | Eksekutif | 650.000|")
    print("|  5 | Tegal           | Ekonomi   | 450.000|")
    print("|  6 | Tegal           | Bisnis    | 520.000|")
    print("|  7 | Tegal           | Eksekutif | 650.000|")
    print("|  8 | Pemalang        | Bisnis    | 520.000|")
    print("|  9 | Pemalang        | Eksekutif | 650.000|")
    print("| 10 | Pekalongan      | Ekonomi   | 450.000|")
    print("| 11 | Pekalongan      | Bisnis    | 520.000|")
    print("| 12 | Pekalongan      | Eksekutif | 650.000|")
    print("| 13 | Weleri          | Ekonomi   | 450.000|")
    print("| 14 | Weleri          | Eksekutif | 650.000|")
    print("| 15 | Semarang Poncol | Ekonomi   | 450.000|")
    print("| 16 | Semarang Poncol | Eksekutif | 650.000|")
    print("| 17 | Semarang Tawang | Ekonomi   | 450.000|")
    print("| 18 | Semarang Tawang | Bisnis    | 520.000|")
    print("| 19 | Semarang Tawang | Eksekutif | 650.000|")
    print("| 20 | Ngrombo         | Ekonomi   | 450.000|")
    print("| 21 | Ngrombo         | Bisnis    | 520.000|")
    print("| 22 | Ngrombo         | Eksekutif | 650.000|")
    print("| 23 | Randublatung    | Ekonomi   | 450.000|")
    print("| 24 | Randublatung    | Eksekutif | 650.000|")
    print("| 25 | Cepu            | Ekonomi   | 450.000|")
    print("| 26 | Cepu            | Bisnis    | 520.000|")
    print("| 27 | Cepu            | Eksekutif | 650.000|")
    print("="*45)
    JSPE = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-27]: ")
    eko = ["1","3","5","10","13","15","17","20","23","25"]
    bis = ["6","8","11","18","21","26"]
    eks = ["2","4","7","9","12","14","22","24","27"]
    if JSPE in eko:
        bayar131()
    elif JSPE in bis:
        bayar231()
    elif JSPE in eks:
        bayar332()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
              
def SJGE():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Gubeng dan Stasiun Kedatangan di Jawa Tengah"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GUBENG                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|               JAWA TENGAH                 |")
    print("|___________________________________________|")
    print("|  1 | Tegal           | Eksekutif | 650.000|")
    print("|  2 | Tegal           | Bisnis    | 520.000|")
    print("|  3 | Tegal           | Eksekutif | 650.000|")
    print("|  4 | Pemalang        | Bisnis    | 520.000|")
    print("|  5 | Pemalang        | Eksekutif | 650.000|")
    print("|  6 | Pekalongan      | Ekonomi   | 450.000|")
    print("|  7 | Pekalongan      | Bisnis    | 520.000|")
    print("|  8 | Pekalongan      | Eksekutif | 650.000|")
    print("|  9 | Weleri          | Ekonomi   | 450.000|")
    print("| 10 | Weleri          | Eksekutif | 650.000|")
    print("| 11 | Semarang Poncol | Ekonomi   | 450.000|")
    print("| 12 | Semarang Poncol | Eksekutif | 650.000|")
    print("| 13 | Ngrombo         | Eksekutif | 650.000|")
    print("| 14 | Ngrombo         | Luxury    | 800.000|")
    print("| 15 | Cepu            | Eksekutif | 650.000|")
    print("| 16 | Cepu            | Luxury    | 800.000|")
    print("| 17 | Purwokerto      | Eksekutif | 650.000|")
    print("| 18 | Purwokerto      | Luxury    | 800.000|")
    print("| 19 | Kroya           | Eksekutif | 650.000|")
    print("| 20 | Kroya           | Luxury    | 800.000|")
    print("| 21 | Kebumen         | Eksekutif | 650.000|")
    print("| 22 | Kebumen         | Luxury    | 800.000|")
    print("| 23 | Kutoarjo        | Eksekutif | 650.000|")
    print("| 24 | Kutoarjo        | Luxury    | 800.000|")
    print("| 25 | Yogyakarta      | Eksekutif | 650.000|")
    print("| 26 | Yogyakarta      | Luxury    | 800.000|")
    print("| 27 | Solo Balapan    | Eksekutif | 650.000|")
    print("| 28 | Solo Balapan    | Luxury    | 800.000|")
    print("="*45)
    SJGE = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-28]: ")
    eko = ["6","9","11"]
    bis = ["2","4","7"]
    eks = ["1","3","5","8","10","12","13","15","17","19","21","23","25","27"]
    lux = ["14","16","18","20","22","24","26","28"]
    if SJGE in eko:
        bayar131()
    elif SJGE in bis:
        bayar231()
    elif SJGE in eks:
        bayar332()
    elif SJGE in lux:
        bayar341()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
              
def SJPE():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Pasar Turi dan Stasiun Kedatangan di Jawa Tengah"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                PASAR TURI                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|               JAWA TENGAH                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Tanjung         | Ekonomi   | 450.000|")
    print("|  2 | Tanjung         | Eksekutif | 650.000|")
    print("|  3 | Brebes          | Ekonomi   | 450.000|")
    print("|  4 | Brebes          | Eksekutif | 650.000|")
    print("|  5 | Tegal           | Eksekutif | 650.000|")
    print("|  6 | Tegal           | Bisnis    | 520.000|")
    print("|  7 | Tegal           | Eksekutif | 650.000|")
    print("|  8 | Pemalang        | Bisnis    | 520.000|")
    print("|  9 | Pemalang        | Eksekutif | 650.000|")
    print("| 10 | Pekalongan      | Ekonomi   | 450.000|")
    print("| 11 | Pekalongan      | Bisnis    | 520.000|")
    print("| 12 | Pekalongan      | Eksekutif | 650.000|")
    print("| 13 | Weleri          | Ekonomi   | 450.000|")
    print("| 14 | Weleri          | Eksekutif | 650.000|")
    print("| 15 | Semarang Poncol | Ekonomi   | 450.000|")
    print("| 16 | Semarang Poncol | Eksekutif | 650.000|")
    print("| 17 | Semarang Tawang | Ekonomi   | 450.000|")
    print("| 18 | Semarang Tawang | Bisnis    | 520.000|")
    print("| 19 | Semarang Tawang | Eksekutif | 650.000|")
    print("| 20 | Ngrombo         | Ekonomi   | 450.000|")
    print("| 21 | Ngrombo         | Bisnis    | 520.000|")
    print("| 22 | Ngrombo         | Eksekutif | 650.000|")
    print("| 23 | Randublatung    | Ekonomi   | 450.000|")
    print("| 24 | Randublatung    | Eksekutif | 650.000|")
    print("| 25 | Cepu            | Ekonomi   | 450.000|")
    print("| 26 | Cepu            | Bisnis    | 520.000|")
    print("| 27 | Cepu            | Eksekutif | 650.000|")
    print("="*45)
    SJPE = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-27]: ")
    ekonomi = ["1","3","10","13","15","17","20","23","25"]
    bisnis = ["6","8","11","18","21","26"]
    eksekutif = ["2","4","5","7","9","12","14","16","19","22","24","27"]
    if SJPE in eksekutif:
        bayar332()
    elif SJPE in ekonomi:
        bayar131()
    elif SJPE in bisnis:
        bayar231()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        

def JSGI():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Gambir dan Stasiun Kedatangan di Jawa Timur"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GAMBIR                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                JAWA TIMUR                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Bojonegoro      | Eksekutif | 650.000|")
    print("|  2 | Bojonegoro      | Luxury    | 800.000|")
    print("|  3 | Lamongan        | Eksekutif | 650.000|")
    print("|  4 | Lamongan        | Luxury    | 800.000|")
    print("|  5 | Madiun          | Eksekutif | 650.000|")
    print("|  6 | Madiun          | Luxury    | 800.000|")
    print("|  7 | Nganjuk         | Eksekutif | 650.000|")
    print("|  8 | Nganjuk         | Luxury    | 800.000|")
    print("|  9 | Kertosono       | Eksekutif | 650.000|")
    print("| 10 | Kertosono       | Luxury    | 800.000|")
    print("| 11 | Jombang         | Eksekutif | 650.000|")
    print("| 12 | Jombang         | Luxury    | 800.000|")
    print("| 13 | Mojokerto       | Eksekutif | 650.000|")
    print("| 14 | Mojokerto       | Luxury    | 800.000|")
    print("="*45)
    JSGI = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-14]: ")
    ekse = ["1","3","5","7","9","11","13"]
    luxu = ["2","4","6","8","10","12","14"]
    if JSGI in ekse:
        bayar332()
    elif JSGI in luxu:
        bayar341()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
              
def JSPI():
    "Jurusan Jakarta Surabaya dengan Stasiun Keberangkatan Pasar Senen dan Stasiun Kedatangan di Jawa Timur"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|               PASAR SENEN                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                JAWA TIMUR                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Bojonegoro      | Eksekutif | 650.000|")
    print("|  2 | Bojonegoro      | Luxury    | 800.000|")
    print("|  3 | Lamongan        | Eksekutif | 650.000|")
    print("|  4 | Lamongan        | Luxury    | 800.000|")
    print("|  5 | Madiun          | Eksekutif | 650.000|")
    print("|  6 | Madiun          | Luxury    | 800.000|")
    print("|  7 | Nganjuk         | Eksekutif | 650.000|")
    print("|  8 | Nganjuk         | Luxury    | 800.000|")
    print("|  9 | Kertosono       | Eksekutif | 650.000|")
    print("| 10 | Kertosono       | Luxury    | 800.000|")
    print("| 11 | Jombang         | Eksekutif | 650.000|")
    print("| 12 | Jombang         | Luxury    | 800.000|")
    print("| 13 | Mojokerto       | Eksekutif | 650.000|")
    print("| 14 | Mojokerto       | Luxury    | 800.000|")
    print("| 15 | Sepanjang       | Eksekutif | 650.000|")
    print("| 16 | Sepanjang       | Luxury    | 800.000|")
    print("="*45)
    JSPI = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-16]: ")
    eks = ["1","3","5","7","9","11","13","15"]
    lux = ["2","4","6","8","10","12","14","16"]
    if JSPI in eks:
        bayar332()
    elif JSPI in lux:
        bayar341()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
              
def SJGI():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Gubeng dan Stasiun Kedatangan di Jawa Timur"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                  GUBENG                   |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                JAWA TIMUR                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Madiun          | Eksekutif | 650.000|")
    print("|  2 | Madiun          | Luxury    | 800.000|")
    print("|  3 | Nganjuk         | Eksekutif | 650.000|")
    print("|  4 | Nganjuk         | Luxury    | 800.000|")
    print("|  5 | Kertosono       | Eksekutif | 650.000|")
    print("|  6 | Kertosono       | Luxury    | 800.000|")
    print("|  7 | Jombang         | Eksekutif | 650.000|")
    print("|  8 | Jombang         | Luxury    | 800.000|")
    print("|  9 | Mojokerto       | Eksekutif | 650.000|")
    print("| 10 | Mojokerto       | Luxury    | 800.000|")
    print("="*45)
    SJGI = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-10]: ")
    ek = ["1","3","5","7","9"]
    lu = ["2","4","6","8","10"]
    if SJGI in ek:
        bayar332()
    elif SJGI in lu:
        bayar341()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
              
def SJPI():
    "Jurusan Surabaya Jakarta dengan Stasiun Keberangkatan Pasar Turi dan Stasiun Kedatangan di Jawa Timur"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|           STASIUN KEBERANGKATAN           |")
    print("|___________________________________________|")
    print("|                PASAR TURI                 |")
    print("|___________________________________________|")
    print("|             STASIUN KEDATANGAN            |")
    print("|___________________________________________|")
    print("|                JAWA BARAT                 |")
    print("|___________________________________________|")
    print("| No | Stasiun         | Kelas     | Harga  |")
    print("|  1 | Bojonegoro      | Eksekutif | 650.000|")
    print("|  2 | Bojonegoro      | Luxury    | 800.000|")
    print("|  3 | Lamongan        | Eksekutif | 650.000|")
    print("|  4 | Lamongan        | Luxury    | 800.000|")
    print("|  5 | Madiun          | Eksekutif | 650.000|")
    print("|  6 | Madiun          | Luxury    | 800.000|")
    print("|  7 | Nganjuk         | Eksekutif | 650.000|")
    print("|  8 | Nganjuk         | Luxury    | 800.000|")
    print("|  9 | Kertosono       | Eksekutif | 650.000|")
    print("| 10 | Kertosono       | Luxury    | 800.000|")
    print("| 11 | Jombang         | Eksekutif | 650.000|")
    print("| 12 | Jombang         | Luxury    | 800.000|")
    print("| 13 | Mojokerto       | Eksekutif | 650.000|")
    print("| 14 | Mojokerto       | Luxury    | 800.000|")
    print("| 15 | Sepanjang       | Eksekutif | 650.000|")
    print("| 16 | Sepanjang       | Luxury    | 800.000|")
    print("="*45)
    SJPI = input("Silahkan masukkan pilihan stasiun tujuan Anda [1-16]: ")
    eksekutif = ["1","3","5","7","9","11","13","15"]
    luxury = ["2","4","6","8","10","12","14","16"]
    if SJPI in eksekutif:
        bayar332()
    elif SJPI in luxury:
        bayar341()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def kel11():
    "Jakarta Surabaya Kelas Ekonomi, Bisnis, Luxury Gambir-Gubeng"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|Mohon maaf tiket tidak tersedia/sudah habis|")
    print("| Silahkan memilih alternatif kelas lainnya |")
    print("="*45)
    
def kel13():
    "Jakarta Surabaya Kelas Eksekutif Gambir-Gubeng"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Bima          |17.05 - 04.36 |450.000 |")
    print("|  2 |Bima          |17.05 - 04.36 |570.000 |")
    print("="*45)
    pilihankel13 = input("Silahkan pilih kereta api yang diinginkan [1-2]: ")
    if pilihankel13 == "1":
        bayar131()
    elif pilihankel13 == "2":
        bayar132()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu") 
    
def kel21():
    "Jakarta Surabaya Kelas Ekomomi Pasar Senen-Gubeng"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Jayabaya      |16.45 - 04.05 |250.000 |")
    print("|  2 |Jayakarta     |17.10 - 06.37 |230.000 |")
    print("="*45)
    pilihankel21 = input("Silahkan pilih kereta api yang diinginkan [1-2]: ")
    if pilihankel21 == "1":
        bayar211()
    elif pilihankel21 == "2":
        bayar212()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def kel23():
    "Jakarta Surabaya Kelas Eksekutif Pasar Senen-Gubeng"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Jayabaya      |16.45 - 04.05 |520.000 |")
    print("|  2 |Jayakarta     |17.10 - 06.37 |330.000 |")
    print("="*45)
    pilihankel23 = input("Silahkan pilih kereta api yang diinginkan [1-2]: ")
    if pilihankel23 == "1":
        bayar231()
    elif pilihankel23 == "2":
        bayar232()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def kel33():
    "Jakarta Surabaya Kelas Eksekutif Gambir-Pasar Turi"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|No| Nama KA          | Waktu       | Harga |")
    print("|1 |Argo Bromo Anggrek|08.20 - 16.30|400.000|")
    print("|2 |Argo Bromo Anggrek|20.35 - 04.45|650.000|")
    print("|3 |Sembrani          |19.00 - 04.30|390.000|")
    print("="*45)
    pilihankel33 = input("Silahkan pilih kereta api yang diinginkan [1-3]: ")
    if pilihankel33 == "1":
        bayar331()
    elif pilihankel33 == "2":
        bayar332()
    elif pilihankel33 == "3":
        bayar333()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def kel34():
    "Jakarta Surabaya Kelas Luxury Gambir-Pasar Turi"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("|No| Nama KA          | Waktu       | Harga |")
    print("|1 |Argo Bromo Anggrek|08.20 - 16.30|800.000|")
    print("|2 |Argo Bromo Anggrek|20.35 - 04.45|950.000|")
    print("|3 |Sembrani          |19.00 - 04.30|800.000|")
    print("="*45)
    pilihankel34 = input("Silahkan pilih kereta api yang diinginkan [1-3]: ")
    if pilihankel34 == "1":
        bayar341()
    elif pilihankel34 == "2":
        bayar342()
    elif pilihankel34 == "3":
        bayar341()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def kel41():
    "Jakarta Surabaya Kelas Ekomomi Pasar Senen-Pasar Turi"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Dharmawangsa  |08.55 - 19.35 |170.000 |")
    print("|  2 |Airlangga     |11.10 - 22.50 |104.000 |")
    print("|  3 |Kertajaya     |14.10 - 01.25 |190.000 |")
    print("|  4 |Jayabaya      |16.45 - 03.39 |250.000 |")
    print("="*45)
    pilihankel41 = input("Silahkan pilih kereta api yang diinginkan [1-4]: ")
    if pilihankel41 == "1":
        bayar411()
    elif pilihankel41 == "2":
        bayar412()
    elif pilihankel41 == "3":
        bayar413()
    elif pilihankel41 == "4":
        bayar211()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
def kel42():
    "Jakarta Surabaya Kelas Bisnis Pasar Senen-Pasar Turi"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Gumarang      |15.50 - 02.45 |240.000 |")
    print("="*45)
    pilihankel42 = input("Silahkan pilih kereta api yang diinginkan [1]: ")
    if pilihankel42 == "1":
        bayar421()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def kel43():
    "Jakarta Surabaya Kelas Eksekutif Pasar Senen-Pasar Turi"
    print("="*45)
    print("|         JURUSAN JAKARTA - SURABAYA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Dharmawangsa  |08.55 - 19.35 |450.000 |")
    print("|  2 |Gumarang      |15.50 - 02.45 |520.000 |")
    print("|  3 |Kertajaya     |14.10 - 01.25 |260.000 |")
    print("|  4 |Jayabaya      |16.45 - 03.39 |520.000 |")
    print("="*45)
    pilihankel43 = input("Silahkan pilih kereta api yang diinginkan [1-4]: ")
    if pilihankel43 == "1":
        bayar131()
    elif pilihankel43 == "2":
        bayar231()
    elif pilihankel43 == "3":
        bayar433()
    elif pilihankel43 == "4":
        bayar231()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def kel51():
    "Jakarta Surabaya Kelas Ekonomi, Bisnis, Luxury Gambir-Gubeng"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|Mohon maaf tiket tidak tersedia/sudah habis|")
    print("| Silahkan memilih alternatif kelas lainnya |")
    print("="*45)
    
def kel53():
    "Surabaya Jakarta Kelas Eksekutif Gubeng-Gambir"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Bima          |17.10 - 04.45 |450.000 |")
    print("|  2 |Bima          |17.10 - 04.45 |570.000 |")
    print("="*45)
    pilihankel53 = input("Silahkan pilih kereta api yang diinginkan [1-2]: ")
    if pilihankel53 == "1":
        bayar131()
    elif pilihankel53 == "2":
        bayar132()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def kel61():
    "Surabaya Jakarta Kelas Ekonomi Gubeng-Pasar Senen"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Jayabaya      |13.56 - 01.25 |250.000 |")
    print("|  2 |Jayakarta     |14.30 - 03.25 |230.000 |")
    print("="*45)
    pilihankel61 = input("Silahkan pilih kereta api yang diinginkan [1-2]: ")
    if pilihankel61 == "1":
        bayar211()
    elif pilihankel61 == "2":
        bayar212()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def kel63():
    "Surabaya Jakarta Kelas Eksekutif Gubeng-Pasar Senen"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Jayabaya      |13.56 - 01.25 |520.000 |")
    print("|  2 |Jayakarta     |14.30 - 03.25 |330.000 |")
    print("="*45)
    pilihankel63 = input("Silahkan pilih kereta api yang diinginkan [1-2]: ")
    if pilihankel63 == "1":
        bayar231()
    elif pilihankel63 == "2":
        bayar232()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def kel73():
    "Surabaya Jakarta Kelas Eksekutif Pasar Turi-Gambir"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|No| Nama KA          | Waktu       | Harga |")
    print("|1 |Argo Bromo Anggrek|09.35 - 17.45|400.000|")
    print("|2 |Argo Bromo Anggrek|21.05 - 05.15|650.000|")
    print("|3 |Sembrani          |18.55 - 04.27|390.000|")
    print("="*45)
    pilihankel73 = input("Silahkan pilih kereta api yang diinginkan [1-3]: ")
    if pilihankel73 == "1":
        bayar331()
    elif pilihankel73 == "2":
        bayar332()
    elif pilihankel73 == "3":
        bayar333()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def kel74():
    "Surabaya Jakarta Kelas Eksekutif Pasar Turi-Gambir"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("|No| Nama KA          | Waktu       | Harga |")
    print("|1 |Argo Bromo Anggrek|09.35 - 17.45|800.000|")
    print("|2 |Argo Bromo Anggrek|21.05 - 05.15|950.000|")
    print("|3 |Sembrani          |18.55 - 04.27|800.000|")
    print("="*45)
    pilihankel74 = input("Silahkan pilih kereta api yang diinginkan [1-3]: ")
    if pilihankel74 == "1":
        bayar341()
    elif pilihankel74 == "2":
        bayar342()
    elif pilihankel74 == "3":
        bayar341()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def kel81():
    "Surabaya Jakarta Kelas Ekomomi Pasar Turi-Pasar Senen"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Dharmawangsa  |22.35 - 09.25 |170.000 |")
    print("|  2 |Airlangga     |12.25 - 00.28 |104.000 |")
    print("|  3 |Kertajaya     |21.20 - 08.35 |190.000 |")
    print("|  4 |Jayabaya      |14.20 - 01.25 |250.000 |")
    print("="*45)
    pilihankel81 = input("Silahkan pilih kereta api yang diinginkan [1-4]: ")
    if pilihankel81 == "1":
        bayar411()
    elif pilihankel81 == "2":
        bayar412()
    elif pilihankel81 == "3":
        bayar413()
    elif pilihankel81 == "4":
        bayar211()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
        
def kel82():
    "Surabaya Jakarta Kelas Bisnis Pasar Turi-Pasar Senen"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Gumarang      |15.55 - 02.42 |240.000 |")
    print("="*45)
    pilihankel82 = input("Silahkan pilih kereta api yang diinginkan [1]: ")
    if pilihankel82 == "1":
        bayar421()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")

def kel83():
    "Surabaya Jakarta Kelas Eksekutif Pasar Turi-Pasar Senen"
    print("="*45)
    print("|         JURUSAN SURABAYA - JAKARTA        |")
    print("="*45)
    print("| No | Nama KA      | Waktu        | Harga  |")
    print("|  1 |Dharmawangsa  |22.35 - 09.25 |450.000 |")
    print("|  2 |Gumarang      |15.55 - 02.42 |520.000 |")
    print("|  3 |Kertajaya     |21.20 - 08.35 |260.000 |")
    print("|  4 |Jayabaya      |14.20 - 01.25 |520.000 |")
    print("="*45)
    pilihankel83 = input("Silahkan pilih kereta api yang diinginkan [1-4]: ")
    if pilihankel83 == "1":
        bayar131()
    elif pilihankel83 == "2":
        bayar231()
    elif pilihankel83 == "3":
        bayar433()
    elif pilihankel83 == "4":
        bayar231()
    else:
        print("Mohon maaf yang Anda pilih tidak terdapat di dalam menu")
    
def bayar131():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 450.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar132():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 570.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar211():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 250.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar212():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 230.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar231():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 520.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar232():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 330.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar331():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 400.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar332():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 650.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar333():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 390.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar341():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 800.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar342():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 950.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar411():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 170.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar412():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 104.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)

def bayar413():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 190.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar433():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 260.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)
    
def bayar433():
    print("="*45)
    print("|                 PEMBAYARAN                |")
    print("|___________________________________________|")
    print("|Total Pembayaran = Rp 240.000              |")
    print("|Terima kasih telah menggunakan layanan kami|")
    print("="*45)

menu()

