echo "==================================="
echo "Tugas 1 SISOP Kelas-B"
echo "==================================="
echo "Nama : Gema Khusnul Ma'rifah"
echo "NPM  : 21083010034"
echo "==================================="
echo "notes:"
echo "==================================="
echo "Halo dunia!"
echo "Ini adalah skrip Bash pertamaku di Linux"

